<?php

$global = array(
    'adminEmail' => 'webmaster@example.com',
    'gender' => array('male' => 'Male', 'female' => 'Female'),
    'boolean' => array('0' => 'No', '1' => 'Yes'),
    'married' => array('single' => 'Single', 'married' => 'Married', 'divorced' => 'Divorced'),
    'payment_mode' => array('cash' => 'Cash', 'cheque' => 'Cheque'),
    'donation_mode' => array('web' => 'Web', 'mobile' => 'Mobile'),
    'payment_status' => array('transferred' => 'Transferred', 'cancelled' => 'Cancelled', 'pending' => 'Pending'),
    'user_payment_status' => array('a' => 'Approved', 'p' => 'Pending', 'c' => 'Cancel'),
    'children' => array('0' => '0', '1' => '1', '2' => '2', '3' => '3', '4' => '4', '5' => '5', '6' => '6', '7' => '7', '8' => '8', '9' => '9', '10' => '10', '11' => '11', '12' => '12', '13' => '13', '14' => '14', '15' => '15'),
    'state' => array(
        '' => "State",
        "AK" => "AK",
        "AL" => "AL",
        "AR" => "AR",
        "AS" => "AS",
        "AZ" => "AZ",
        "CA" => "CA",
        "CO" => "CO",
        "CT" => "CT",
        "DC" => "DC",
        "DE" => "DE",
        "FL" => "FL",
        "FM" => "FM",
        "GA" => "GA",
        "GU" => "GU",
        "HI" => "HI",
        "IA" => "IA",
        "ID" => "ID",
        "IL" => "IL",
        "IN" => "IN",
        "KS" => "KS",
        "KY" => "KY",
        "LA" => "LA",
        "MA" => "MA",
        "MD" => "MD",
        "ME" => "ME",
        "MH" => "MH",
        "MI" => "MI",
        "MN" => "MN",
        "MO" => "MO",
        "MP" => "MP",
        "MS" => "MS",
        "MT" => "MT",
        "NC" => "NC",
        "ND" => "ND",
        "NE" => "NE",
        "NH" => "NH",
        "NJ" => "NJ",
        "NM" => "NM",
        "NV" => "NV",
        "NY" => "NY",
        "OH" => "OH",
        "OK" => "OK",
        "OR" => "OR",
        "PA" => "PA",
        "PR" => "PR",
        "PW" => "PW",
        "RI" => "RI",
        "SC" => "SC",
        "SD" => "SD",
        "TN" => "TN",
        "TX" => "TX",
        "UM" => "UM",
        "UT" => "UT",
        "VA" => "VA",
        "VI" => "VI",
        "VT" => "VT",
        "WA" => "WA",
        "WI" => "WI",
        "WV" => "WV",
        "WY" => "WY"
    )
);
?>